config/routes.rb
InventoryMgmtJasonMarch20::Application.routes.draw do
  resources :search4s

  resources :search3s

  resources :search2s

  resources :searches

  resources :sales

  resources :items

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :item

  accepts_nested_attributes_for :item

def items
    @items ||= find_items
    #@sales ||= find_items2

  end
  def rer
    Sale.where(:item_id => item_id).where('sale_date >= ?', s_date).where('sale_date <= ?', e_date)
  end

  private
  def find_items
    items = Item.where(:id => item_id) if item_id.present?

    items

  end

#def find_items2
#
#  items = Sale.where("date >= ?" => s_date) if s_date.present?
#  items = Sale.where("date <= ?" =>  e_date) if e_date.present?
#  items
#end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_search
    @search = Search.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def search_params
    params.require(:search).permit(:item_id, :s_date, :e_date)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
    <% if @search.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

          <ul>
            <% @search.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :item_id %><br>
      <%= f.collection_select :item_id, Item.all , :id, :item_name, prompt: true %>

    </div>
    <div class="field">
      <%= f.label :s_date %><br>
      <%= f.date_select :s_date %>
    </div>
    <div class="field">
      <%= f.label :e_date %><br>
      <%= f.date_select :e_date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Items Sold in a Given Time Period</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.item_id %></td>
        <td><%= search.s_date %></td>
        <td><%= search.e_date %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<h1>Heading</h1>

<%= render 'items/item'%>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>