config/routes.rb
InventoryMgmtJasonMarch20::Application.routes.draw do
  resources :search4s

  resources :search3s

  resources :search2s

  resources :searches

  resources :sales

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :sales
  has_many :searches
  has_many :search2s
  has_many :search3s
  has_many :search4s
  validates :amount, :numericality => { :greater_than_or_equal_to => 0 }
  validates_presence_of :item_name, :price, :amount, :min_amount

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:item_name, :price, :amount, :min_amount)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :item_name %><br>
      <%= f.text_field :item_name %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :amount %><br>
      <%= f.number_field :amount %>
    </div>
    <div class="field">
      <%= f.label :min_amount %><br>
      <%= f.number_field :min_amount %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/items/_item.html.erb
<div class="item">


  <div class="details">

    <%r= @search.rer %>
    <%=  Sale.where(:item_id => r).sum('amount_sold')%>
  </div>
</div>

app/views/items/_item2.html.erb
<div class="item">

  <div class="details">
    <%i= @search2.items2%>
    <%r= @search2.d_val %>
    <%a=  Sale.where(:item_id => r).sum('amount_sold')%>
    <%b = Item.where(:id => 1).sum('price')%>
    <%= a*b%>
  </div></div>




app/views/items/_item3.html.erb
<h>Title</h>
<div class="item">
  <%item=@search3.items3%>
  <div class="details">

    <% a = Item.where(:id => item).sum('amount')%>
    <% b = Item.where(:id => item).sum('min_amount')%>
    <%= "Current Stock: #{a} Min Stock: #{b}" %>

  </div></div>

app/views/items/_item4.html.erb
<h>Title</h>
<div class="item">
  <%item=@search4.items4%>

  <div class="details">
    <% e = Date.today%>
    <% d=  e - 7%>
    <%a= Sale.where(:item_id => item).average(:amount_sold)%>
    <%b= Item.where(:id => item).sum('price')%>
    <%c= Sale.where("date > #{d}").where("date < #{e}")%>
    <%= "Average Sold: #{a} Price per Item: #{b} For after #{d} and before #{e}" %>







  </div></div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>

      <th>Price</th>
      <th>Amount on Hand</th>
      <th>Minimum amount allowed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.price %></td>
        <td><%= item.amount %></td>
        <td><%= item.min_amount %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h>Inventory</h>
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @item.item_name %>
</p>

<br>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<p>
  <strong>Min amount:</strong>
  <%= @item.min_amount %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>