config/routes.rb
InventoryMgmtJasonMarch20::Application.routes.draw do
  resources :search4s

  resources :search3s

  resources :search2s

  resources :searches

  resources :sales

  resources :items

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :item
  accepts_nested_attributes_for :item
  validates :amount_sold, :numericality => { :greater_than_or_equal_to => 0 }
  validates_presence_of :item_id, :sale_date, :amount_sold





end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    params.require(:sale).permit(:item_id, :sale_date, :amount_sold)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
    <% if @sale.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

          <ul>
            <% @sale.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :item_id %><br>
      <%= f.collection_select :item_id, Item.all , :id, :item_name, prompt: true %>
    </div>
    <div class="field">
      <%= f.label :sale_date %><br>
      <%= f.date_select :sale_date %>
    </div>
    <div class="field">
      <%= f.label :amount_sold %><br>
      <%= f.number_field :amount_sold %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Sale Date</th>
      <th>Amount sold</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.item_id %></td>
        <td><%= sale.sale_date %></td>
        <td><%= sale.amount_sold %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<h>Sales</h>
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @sale.item_id %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<p>
  <strong>Amount sold:</strong>
  <%= @sale.amount_sold %>
</p>

<%= link_to 'Sale Successful, please update inventory', items_path %>
<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>